version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/app/static/uploads
    environment:
      - FLASK_CONFIG=production
      - SECRET_KEY=change_this_in_production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/amf_motorsports
      - LOG_TO_STDOUT=1
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=amf_motorsports
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
